In [1]:
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog
import cv2

In [2]:
import pandas as pd

df = pd.read_csv('ramification/train_labels.csv')

df.head()

filename  width  height         class  xmin  ymin  xmax  ymax
0  mask_0.jpg    640     800  ramification     8   303    64   348
1  mask_0.jpg    640     800  ramification     9   209    62   248
2  mask_0.jpg    640     800  ramification   300   223   370   276
3  mask_0.jpg    640     800  ramification   312   193   360   234
4  mask_0.jpg    640     800  ramification   312    88   357   129

In [3]:
import os
import numpy as np
import json
from detectron2.structures import BoxMode
import itertools
import cv2

def get_ramification_dicts(csv_file, img_dir):
    df = pd.read_csv(csv_file)
    df['filename'] = df['filename'].map(lambda x: img_dir+x)

    classes = ['ramification']
    df['class'] = df['class'].map(lambda x: 'ramification')
    df['class_int'] = df['class'].map(lambda x: classes.index(x))

    dataset_dicts = []
    for filename in df['filename'].unique().tolist():
        record = {}
        print(filename)
        image = cv2.imread(filename)
        print(image)
        height, width, _ = image.shape
        
        record["file_name"] = filename
        record["height"] = height
        record["width"] = width

        objs = []
        for index, row in df[(df['filename']==filename)].iterrows():
          obj= {
              'bbox': [row['xmin'], row['ymin'], row['xmax'], row['ymax']],
              'bbox_mode': BoxMode.XYXY_ABS,
              'category_id': row['class_int'],
              "iscrowd": 0
          }
          objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts

In [4]:
from detectron2.data import DatasetCatalog, MetadataCatalog

classes = ['ramification']

for d in ["train", "test"]:
  DatasetCatalog.register('ramification_data/' + d, lambda d=d: get_ramification_dicts('ramification/' + d + '_labels.csv', 'ramification/' + d+'/'))
  MetadataCatalog.get('ramification_data/' + d).set(thing_classes=classes)
ramification_metadata = MetadataCatalog.get('ramification_data/train')


In [5]:
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.utils.logger import setup_logger
setup_logger()
cfg = get_cfg()
cfg.merge_from_file("./detectron2/model_zoo/configs/COCO-Detection/retinanet_R_101_FPN_3x.yaml")
cfg.MODEL.WEIGHTS = "model_final_59f53c.pkl"
cfg.DATASETS.TRAIN = ('ramification_data/train',)
cfg.DATASETS.TEST = ()   
cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.MAX_ITER = 20000
cfg.MODEL.RETINANET.NUM_CLASSES = 1
cfg.SOLVER.BASE_LR = 0.0001
cfg.MODEL.DEVICE = "cuda:2"
cfg.OUTPUT_DIR = 'output_model/'
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

Loading config ./detectron2/model_zoo/configs/COCO-Detection/../Base-RetinaNet.yaml with yaml.unsafe_load. Your machine may be at risk if the file contains malicious content.


WARNING [02/02 17:48:56 d2.config.compat]: Config './detectron2/model_zoo/configs/COCO-Detection/retinanet_R_101_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
[02/02 17:48:58 d2.engine.defaults]: Model:
RetinaNet(
  (backbone): FPN(
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelP6P7(
      (p6): Conv2d(2048, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (p7): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    )
    (bottom_up): ResNet(
      (stem): BasicStem(
        (co

ramification/train/mask_0.jpg
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [253 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [253 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [253 255 255]
  [255 255 255]
  [255 255 255]]]
ramification/train/mask_1.jpg
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
ramification/train/mask_147.jpg
[[[255 254 255]
  [255 254 255]
  [255 252 253]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 253 254]
  [255 254 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[251 255 255]
  [248 253 252]
  [253 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [2

[[[255 255 255]
  [255 254 254]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [252 252 252]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[250 252 252]
  [253 255 255]
  [253 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
ramification/train/mask_5.jpg
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
ramification/train/mask_89.jpg
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [25

/home/analiza_obrazu/anaconda3/envs/triffid/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/analiza_obrazu/anaconda3/envs/triffid/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/analiza_obrazu/anaconda3/envs/triffid/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)]

[02/02 17:49:00 d2.engine.train_loop]: Starting training from iteration 0
[02/02 17:49:17 d2.utils.events]: eta: 4:26:00  iter: 19  total_loss: 1.862  loss_cls: 1.090  loss_box_reg: 0.774  time: 0.8044  data_time: 0.0052  lr: 0.000002  max_mem: 0M
[02/02 17:49:33 d2.utils.events]: eta: 4:28:04  iter: 39  total_loss: 1.861  loss_cls: 1.083  loss_box_reg: 0.783  time: 0.8130  data_time: 0.0046  lr: 0.000004  max_mem: 0M
[02/02 17:49:50 d2.utils.events]: eta: 4:33:50  iter: 59  total_loss: 1.801  loss_cls: 1.063  loss_box_reg: 0.737  time: 0.8185  data_time: 0.0048  lr: 0.000006  max_mem: 0M
[02/02 17:50:06 d2.utils.events]: eta: 4:29:13  iter: 79  total_loss: 1.739  loss_cls: 1.038  loss_box_reg: 0.705  time: 0.8186  data_time: 0.0049  lr: 0.000008  max_mem: 0M
[02/02 17:50:23 d2.utils.events]: eta: 4:37:05  iter: 99  total_loss: 1.639  loss_cls: 0.994  loss_box_reg: 0.644  time: 0.8218  data_time: 0.0048  lr: 0.000010  max_mem: 0M
[02/02 17:50:39 d2.utils.events]: eta: 4:36:13  iter: 11

[02/02 18:01:35 d2.utils.events]: eta: 4:20:59  iter: 919  total_loss: 0.552  loss_cls: 0.296  loss_box_reg: 0.234  time: 0.8187  data_time: 0.0043  lr: 0.000092  max_mem: 0M
[02/02 18:01:52 d2.utils.events]: eta: 4:20:55  iter: 939  total_loss: 0.513  loss_cls: 0.286  loss_box_reg: 0.230  time: 0.8193  data_time: 0.0045  lr: 0.000094  max_mem: 0M
[02/02 18:02:09 d2.utils.events]: eta: 4:20:46  iter: 959  total_loss: 0.512  loss_cls: 0.285  loss_box_reg: 0.218  time: 0.8197  data_time: 0.0043  lr: 0.000096  max_mem: 0M
[02/02 18:02:25 d2.utils.events]: eta: 4:20:16  iter: 979  total_loss: 0.547  loss_cls: 0.307  loss_box_reg: 0.238  time: 0.8193  data_time: 0.0043  lr: 0.000098  max_mem: 0M
[02/02 18:02:41 d2.utils.events]: eta: 4:20:00  iter: 999  total_loss: 0.515  loss_cls: 0.297  loss_box_reg: 0.227  time: 0.8194  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 18:02:58 d2.utils.events]: eta: 4:20:11  iter: 1019  total_loss: 0.501  loss_cls: 0.276  loss_box_reg: 0.228  time: 0.

[02/02 18:13:57 d2.utils.events]: eta: 4:11:43  iter: 1819  total_loss: 0.357  loss_cls: 0.186  loss_box_reg: 0.164  time: 0.8210  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 18:14:13 d2.utils.events]: eta: 4:12:08  iter: 1839  total_loss: 0.338  loss_cls: 0.179  loss_box_reg: 0.159  time: 0.8210  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:14:30 d2.utils.events]: eta: 4:12:22  iter: 1859  total_loss: 0.328  loss_cls: 0.172  loss_box_reg: 0.158  time: 0.8210  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 18:14:46 d2.utils.events]: eta: 4:12:05  iter: 1879  total_loss: 0.318  loss_cls: 0.164  loss_box_reg: 0.152  time: 0.8208  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:15:03 d2.utils.events]: eta: 4:12:08  iter: 1899  total_loss: 0.342  loss_cls: 0.175  loss_box_reg: 0.159  time: 0.8211  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 18:15:18 d2.utils.events]: eta: 4:10:33  iter: 1919  total_loss: 0.322  loss_cls: 0.165  loss_box_reg: 0.158  tim

[02/02 18:26:06 d2.utils.events]: eta: 3:55:50  iter: 2719  total_loss: 0.209  loss_cls: 0.108  loss_box_reg: 0.104  time: 0.8173  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 18:26:23 d2.utils.events]: eta: 3:55:24  iter: 2739  total_loss: 0.207  loss_cls: 0.107  loss_box_reg: 0.104  time: 0.8172  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 18:26:39 d2.utils.events]: eta: 3:55:20  iter: 2759  total_loss: 0.218  loss_cls: 0.105  loss_box_reg: 0.109  time: 0.8173  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:26:55 d2.utils.events]: eta: 3:54:52  iter: 2779  total_loss: 0.192  loss_cls: 0.092  loss_box_reg: 0.099  time: 0.8172  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 18:27:11 d2.utils.events]: eta: 3:52:40  iter: 2799  total_loss: 0.213  loss_cls: 0.103  loss_box_reg: 0.104  time: 0.8171  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 18:27:27 d2.utils.events]: eta: 3:52:11  iter: 2819  total_loss: 0.202  loss_cls: 0.100  loss_box_reg: 0.098  tim

[02/02 18:38:18 d2.utils.events]: eta: 3:43:33  iter: 3619  total_loss: 0.134  loss_cls: 0.060  loss_box_reg: 0.071  time: 0.8159  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:38:34 d2.utils.events]: eta: 3:44:11  iter: 3639  total_loss: 0.124  loss_cls: 0.057  loss_box_reg: 0.061  time: 0.8160  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 18:38:50 d2.utils.events]: eta: 3:44:08  iter: 3659  total_loss: 0.126  loss_cls: 0.061  loss_box_reg: 0.065  time: 0.8159  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 18:39:06 d2.utils.events]: eta: 3:43:21  iter: 3679  total_loss: 0.115  loss_cls: 0.051  loss_box_reg: 0.064  time: 0.8158  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 18:39:22 d2.utils.events]: eta: 3:42:43  iter: 3699  total_loss: 0.120  loss_cls: 0.056  loss_box_reg: 0.066  time: 0.8157  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:39:39 d2.utils.events]: eta: 3:42:48  iter: 3719  total_loss: 0.129  loss_cls: 0.059  loss_box_reg: 0.063  tim

[02/02 18:50:31 d2.utils.events]: eta: 3:33:05  iter: 4519  total_loss: 0.085  loss_cls: 0.038  loss_box_reg: 0.047  time: 0.8156  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 18:50:48 d2.utils.events]: eta: 3:32:52  iter: 4539  total_loss: 0.077  loss_cls: 0.034  loss_box_reg: 0.044  time: 0.8155  data_time: 0.0041  lr: 0.000100  max_mem: 0M
[02/02 18:51:03 d2.utils.events]: eta: 3:32:51  iter: 4559  total_loss: 0.073  loss_cls: 0.031  loss_box_reg: 0.043  time: 0.8154  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:51:20 d2.utils.events]: eta: 3:33:19  iter: 4579  total_loss: 0.079  loss_cls: 0.037  loss_box_reg: 0.041  time: 0.8154  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 18:51:36 d2.utils.events]: eta: 3:33:26  iter: 4599  total_loss: 0.082  loss_cls: 0.035  loss_box_reg: 0.043  time: 0.8155  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 18:51:52 d2.utils.events]: eta: 3:33:54  iter: 4619  total_loss: 0.079  loss_cls: 0.036  loss_box_reg: 0.044  tim

[02/02 19:02:41 d2.utils.events]: eta: 3:19:10  iter: 5419  total_loss: 0.056  loss_cls: 0.023  loss_box_reg: 0.030  time: 0.8145  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:02:57 d2.utils.events]: eta: 3:18:33  iter: 5439  total_loss: 0.061  loss_cls: 0.026  loss_box_reg: 0.035  time: 0.8145  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 19:03:14 d2.utils.events]: eta: 3:18:22  iter: 5459  total_loss: 0.057  loss_cls: 0.023  loss_box_reg: 0.032  time: 0.8146  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 19:03:30 d2.utils.events]: eta: 3:18:00  iter: 5479  total_loss: 0.057  loss_cls: 0.026  loss_box_reg: 0.029  time: 0.8145  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:03:46 d2.utils.events]: eta: 3:17:37  iter: 5499  total_loss: 0.054  loss_cls: 0.023  loss_box_reg: 0.031  time: 0.8145  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 19:04:03 d2.utils.events]: eta: 3:17:21  iter: 5519  total_loss: 0.052  loss_cls: 0.024  loss_box_reg: 0.030  tim

[02/02 19:14:52 d2.utils.events]: eta: 3:07:33  iter: 6319  total_loss: 0.039  loss_cls: 0.016  loss_box_reg: 0.024  time: 0.8142  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:15:09 d2.utils.events]: eta: 3:07:16  iter: 6339  total_loss: 0.038  loss_cls: 0.017  loss_box_reg: 0.021  time: 0.8142  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:15:25 d2.utils.events]: eta: 3:06:50  iter: 6359  total_loss: 0.039  loss_cls: 0.016  loss_box_reg: 0.024  time: 0.8142  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 19:15:41 d2.utils.events]: eta: 3:06:10  iter: 6379  total_loss: 0.041  loss_cls: 0.016  loss_box_reg: 0.024  time: 0.8141  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:15:56 d2.utils.events]: eta: 3:05:45  iter: 6399  total_loss: 0.042  loss_cls: 0.017  loss_box_reg: 0.024  time: 0.8140  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 19:16:13 d2.utils.events]: eta: 3:05:30  iter: 6419  total_loss: 0.040  loss_cls: 0.016  loss_box_reg: 0.024  tim

[02/02 19:27:01 d2.utils.events]: eta: 2:50:25  iter: 7219  total_loss: 0.028  loss_cls: 0.011  loss_box_reg: 0.018  time: 0.8135  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 19:27:18 d2.utils.events]: eta: 2:50:37  iter: 7239  total_loss: 0.031  loss_cls: 0.011  loss_box_reg: 0.018  time: 0.8136  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:27:34 d2.utils.events]: eta: 2:49:53  iter: 7259  total_loss: 0.027  loss_cls: 0.010  loss_box_reg: 0.017  time: 0.8135  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:27:49 d2.utils.events]: eta: 2:49:25  iter: 7279  total_loss: 0.029  loss_cls: 0.010  loss_box_reg: 0.018  time: 0.8135  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:28:06 d2.utils.events]: eta: 2:49:21  iter: 7299  total_loss: 0.028  loss_cls: 0.012  loss_box_reg: 0.017  time: 0.8135  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:28:22 d2.utils.events]: eta: 2:49:39  iter: 7319  total_loss: 0.028  loss_cls: 0.011  loss_box_reg: 0.017  tim

[02/02 19:39:16 d2.utils.events]: eta: 2:45:31  iter: 8119  total_loss: 0.021  loss_cls: 0.008  loss_box_reg: 0.013  time: 0.8138  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:39:33 d2.utils.events]: eta: 2:45:15  iter: 8139  total_loss: 0.025  loss_cls: 0.008  loss_box_reg: 0.016  time: 0.8138  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 19:39:49 d2.utils.events]: eta: 2:44:57  iter: 8159  total_loss: 0.021  loss_cls: 0.007  loss_box_reg: 0.014  time: 0.8138  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:40:05 d2.utils.events]: eta: 2:44:37  iter: 8179  total_loss: 0.026  loss_cls: 0.010  loss_box_reg: 0.016  time: 0.8139  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 19:40:22 d2.utils.events]: eta: 2:44:25  iter: 8199  total_loss: 0.022  loss_cls: 0.008  loss_box_reg: 0.014  time: 0.8139  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:40:38 d2.utils.events]: eta: 2:44:08  iter: 8219  total_loss: 0.020  loss_cls: 0.007  loss_box_reg: 0.013  tim

[02/02 19:51:28 d2.utils.events]: eta: 2:32:08  iter: 9019  total_loss: 0.021  loss_cls: 0.007  loss_box_reg: 0.015  time: 0.8137  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:51:44 d2.utils.events]: eta: 2:30:57  iter: 9039  total_loss: 0.021  loss_cls: 0.007  loss_box_reg: 0.014  time: 0.8136  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 19:52:00 d2.utils.events]: eta: 2:31:07  iter: 9059  total_loss: 0.020  loss_cls: 0.007  loss_box_reg: 0.013  time: 0.8136  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 19:52:17 d2.utils.events]: eta: 2:30:41  iter: 9079  total_loss: 0.021  loss_cls: 0.008  loss_box_reg: 0.014  time: 0.8137  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 19:52:32 d2.utils.events]: eta: 2:29:57  iter: 9099  total_loss: 0.019  loss_cls: 0.007  loss_box_reg: 0.013  time: 0.8136  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 19:52:49 d2.utils.events]: eta: 2:29:03  iter: 9119  total_loss: 0.021  loss_cls: 0.007  loss_box_reg: 0.013  tim

[02/02 20:03:40 d2.utils.events]: eta: 2:18:08  iter: 9919  total_loss: 0.015  loss_cls: 0.006  loss_box_reg: 0.011  time: 0.8136  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 20:03:57 d2.utils.events]: eta: 2:17:52  iter: 9939  total_loss: 0.015  loss_cls: 0.005  loss_box_reg: 0.010  time: 0.8136  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 20:04:13 d2.utils.events]: eta: 2:17:57  iter: 9959  total_loss: 0.015  loss_cls: 0.004  loss_box_reg: 0.010  time: 0.8137  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:04:29 d2.utils.events]: eta: 2:17:41  iter: 9979  total_loss: 0.014  loss_cls: 0.005  loss_box_reg: 0.010  time: 0.8137  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:04:46 d2.utils.events]: eta: 2:17:02  iter: 9999  total_loss: 0.015  loss_cls: 0.005  loss_box_reg: 0.010  time: 0.8136  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 20:05:01 d2.utils.events]: eta: 2:16:49  iter: 10019  total_loss: 0.015  loss_cls: 0.004  loss_box_reg: 0.010  ti

[02/02 20:15:55 d2.utils.events]: eta: 2:06:07  iter: 10819  total_loss: 0.013  loss_cls: 0.004  loss_box_reg: 0.009  time: 0.8137  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 20:16:11 d2.utils.events]: eta: 2:05:56  iter: 10839  total_loss: 0.014  loss_cls: 0.004  loss_box_reg: 0.010  time: 0.8137  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 20:16:26 d2.utils.events]: eta: 2:05:21  iter: 10859  total_loss: 0.014  loss_cls: 0.005  loss_box_reg: 0.009  time: 0.8136  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:16:42 d2.utils.events]: eta: 2:05:15  iter: 10879  total_loss: 0.013  loss_cls: 0.004  loss_box_reg: 0.009  time: 0.8136  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:16:58 d2.utils.events]: eta: 2:04:53  iter: 10899  total_loss: 0.013  loss_cls: 0.004  loss_box_reg: 0.009  time: 0.8135  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 20:17:14 d2.utils.events]: eta: 2:04:35  iter: 10919  total_loss: 0.013  loss_cls: 0.004  loss_box_reg: 0.00

[02/02 20:28:07 d2.utils.events]: eta: 1:55:07  iter: 11719  total_loss: 0.012  loss_cls: 0.004  loss_box_reg: 0.008  time: 0.8136  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 20:28:23 d2.utils.events]: eta: 1:54:24  iter: 11739  total_loss: 0.012  loss_cls: 0.003  loss_box_reg: 0.009  time: 0.8136  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 20:28:39 d2.utils.events]: eta: 1:54:07  iter: 11759  total_loss: 0.012  loss_cls: 0.003  loss_box_reg: 0.008  time: 0.8136  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 20:28:56 d2.utils.events]: eta: 1:53:37  iter: 11779  total_loss: 0.011  loss_cls: 0.003  loss_box_reg: 0.008  time: 0.8137  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:29:12 d2.utils.events]: eta: 1:53:27  iter: 11799  total_loss: 0.012  loss_cls: 0.004  loss_box_reg: 0.008  time: 0.8136  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 20:29:29 d2.utils.events]: eta: 1:53:17  iter: 11819  total_loss: 0.012  loss_cls: 0.004  loss_box_reg: 0.00

[02/02 20:40:13 d2.utils.events]: eta: 1:38:39  iter: 12619  total_loss: 0.010  loss_cls: 0.003  loss_box_reg: 0.007  time: 0.8130  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:40:29 d2.utils.events]: eta: 1:38:16  iter: 12639  total_loss: 0.010  loss_cls: 0.003  loss_box_reg: 0.007  time: 0.8130  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 20:40:46 d2.utils.events]: eta: 1:38:11  iter: 12659  total_loss: 0.010  loss_cls: 0.003  loss_box_reg: 0.007  time: 0.8131  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 20:41:02 d2.utils.events]: eta: 1:38:21  iter: 12679  total_loss: 0.010  loss_cls: 0.003  loss_box_reg: 0.007  time: 0.8131  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 20:41:18 d2.utils.events]: eta: 1:37:30  iter: 12699  total_loss: 0.009  loss_cls: 0.003  loss_box_reg: 0.007  time: 0.8131  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 20:41:34 d2.utils.events]: eta: 1:37:26  iter: 12719  total_loss: 0.010  loss_cls: 0.003  loss_box_reg: 0.00

[02/02 20:52:26 d2.utils.events]: eta: 1:28:53  iter: 13519  total_loss: 0.009  loss_cls: 0.002  loss_box_reg: 0.007  time: 0.8131  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 20:52:42 d2.utils.events]: eta: 1:28:36  iter: 13539  total_loss: 0.009  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8131  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 20:52:58 d2.utils.events]: eta: 1:28:16  iter: 13559  total_loss: 0.010  loss_cls: 0.002  loss_box_reg: 0.007  time: 0.8131  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:53:14 d2.utils.events]: eta: 1:28:02  iter: 13579  total_loss: 0.009  loss_cls: 0.003  loss_box_reg: 0.007  time: 0.8130  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 20:53:30 d2.utils.events]: eta: 1:27:40  iter: 13599  total_loss: 0.009  loss_cls: 0.002  loss_box_reg: 0.007  time: 0.8130  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 20:53:46 d2.utils.events]: eta: 1:27:06  iter: 13619  total_loss: 0.009  loss_cls: 0.002  loss_box_reg: 0.00

[02/02 21:04:37 d2.utils.events]: eta: 1:16:40  iter: 14419  total_loss: 0.009  loss_cls: 0.003  loss_box_reg: 0.006  time: 0.8130  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 21:04:54 d2.utils.events]: eta: 1:16:30  iter: 14439  total_loss: 0.010  loss_cls: 0.002  loss_box_reg: 0.007  time: 0.8131  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 21:05:10 d2.utils.events]: eta: 1:16:12  iter: 14459  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8130  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 21:05:26 d2.utils.events]: eta: 1:15:55  iter: 14479  total_loss: 0.009  loss_cls: 0.003  loss_box_reg: 0.006  time: 0.8130  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:05:42 d2.utils.events]: eta: 1:15:40  iter: 14499  total_loss: 0.009  loss_cls: 0.002  loss_box_reg: 0.007  time: 0.8130  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 21:05:59 d2.utils.events]: eta: 1:15:25  iter: 14519  total_loss: 0.009  loss_cls: 0.003  loss_box_reg: 0.00

[02/02 21:16:50 d2.utils.events]: eta: 1:04:29  iter: 15319  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8130  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:17:06 d2.utils.events]: eta: 1:04:07  iter: 15339  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8129  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:17:22 d2.utils.events]: eta: 1:03:45  iter: 15359  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8129  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 21:17:38 d2.utils.events]: eta: 1:03:33  iter: 15379  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8129  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 21:17:54 d2.utils.events]: eta: 1:03:17  iter: 15399  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8129  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 21:18:11 d2.utils.events]: eta: 1:03:01  iter: 15419  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.00

[02/02 21:29:02 d2.utils.events]: eta: 0:51:51  iter: 16219  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8129  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 21:29:18 d2.utils.events]: eta: 0:51:35  iter: 16239  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8129  data_time: 0.0047  lr: 0.000100  max_mem: 0M
[02/02 21:29:34 d2.utils.events]: eta: 0:51:16  iter: 16259  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8129  data_time: 0.0042  lr: 0.000100  max_mem: 0M
[02/02 21:29:50 d2.utils.events]: eta: 0:51:05  iter: 16279  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.006  time: 0.8129  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 21:30:06 d2.utils.events]: eta: 0:50:43  iter: 16299  total_loss: 0.006  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8129  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 21:30:23 d2.utils.events]: eta: 0:50:38  iter: 16319  total_loss: 0.008  loss_cls: 0.002  loss_box_reg: 0.00

[02/02 21:41:15 d2.utils.events]: eta: 0:39:35  iter: 17119  total_loss: 0.006  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 21:41:31 d2.utils.events]: eta: 0:39:21  iter: 17139  total_loss: 0.006  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:41:47 d2.utils.events]: eta: 0:39:08  iter: 17159  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:42:04 d2.utils.events]: eta: 0:39:01  iter: 17179  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 21:42:21 d2.utils.events]: eta: 0:38:56  iter: 17199  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 21:42:37 d2.utils.events]: eta: 0:38:34  iter: 17219  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.00

[02/02 21:53:30 d2.utils.events]: eta: 0:27:36  iter: 18019  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.005  time: 0.8131  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 21:53:46 d2.utils.events]: eta: 0:27:18  iter: 18039  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8131  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:54:02 d2.utils.events]: eta: 0:26:59  iter: 18059  total_loss: 0.007  loss_cls: 0.002  loss_box_reg: 0.005  time: 0.8131  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 21:54:17 d2.utils.events]: eta: 0:26:38  iter: 18079  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 21:54:34 d2.utils.events]: eta: 0:26:17  iter: 18099  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.005  time: 0.8130  data_time: 0.0041  lr: 0.000100  max_mem: 0M
[02/02 21:54:50 d2.utils.events]: eta: 0:26:04  iter: 18119  total_loss: 0.006  loss_cls: 0.002  loss_box_reg: 0.00

[02/02 22:05:37 d2.utils.events]: eta: 0:14:36  iter: 18919  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8128  data_time: 0.0041  lr: 0.000100  max_mem: 0M
[02/02 22:05:53 d2.utils.events]: eta: 0:14:16  iter: 18939  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8128  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 22:06:09 d2.utils.events]: eta: 0:13:54  iter: 18959  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8128  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 22:06:26 d2.utils.events]: eta: 0:13:37  iter: 18979  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8128  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 22:06:42 d2.utils.events]: eta: 0:13:22  iter: 18999  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8128  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 22:06:59 d2.utils.events]: eta: 0:13:07  iter: 19019  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.00

[02/02 22:17:44 d2.utils.events]: eta: 0:02:24  iter: 19819  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8126  data_time: 0.0043  lr: 0.000100  max_mem: 0M
[02/02 22:18:01 d2.utils.events]: eta: 0:02:08  iter: 19839  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8125  data_time: 0.0044  lr: 0.000100  max_mem: 0M
[02/02 22:18:16 d2.utils.events]: eta: 0:01:52  iter: 19859  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8125  data_time: 0.0046  lr: 0.000100  max_mem: 0M
[02/02 22:18:33 d2.utils.events]: eta: 0:01:36  iter: 19879  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8125  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 22:18:49 d2.utils.events]: eta: 0:01:20  iter: 19899  total_loss: 0.005  loss_cls: 0.001  loss_box_reg: 0.004  time: 0.8125  data_time: 0.0045  lr: 0.000100  max_mem: 0M
[02/02 22:19:05 d2.utils.events]: eta: 0:01:04  iter: 19919  total_loss: 0.006  loss_cls: 0.001  loss_box_reg: 0.00

OrderedDict()